import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <nav className="flex items-center p-4 px-7 bg-[#186578] text-white">
          <a href="/" className="grow text-white">
            Home
          </a>
          <div className="grow flex flex-row justify-end gap-3">
            <a href="/test" className="text-white">
              Test
            </a>
            <a href="/page" className="text-white">
              Page
            </a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
